patch:
  prs:
    comment: >
      PR marked as a patch
    unlabel:
      - 'minor'
      - 'major'

minor:
  prs:
    comment: >
      PR marked as a minor change
    unlabel:
      - 'patch'
      - 'major'

major:
  prs:
    comment: >
      PR marked as a major change
    unlabel:
      - 'patch'
      - 'minor'
    