# Caution: this cluster role provides access to all resources in the cluster
# An all-access cluster role is not recommended for production use.
# This cluster role is intended for testing purposes only.
# Provide access only to the resources you want to listen in a production environment.
# Skip ClusterRole altogether if you want listen to the resources only in a specific namespace, go with a Role.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventsrunner-cluster-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventsrunner-cluster-role-binding
  namespace: eventsrunner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventsrunner-cluster-role
subjects:
  - kind: ServiceAccount
    name: eventsrunner-service-account
    namespace: eventsrunner

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventsrunner-service-account
  namespace: eventsrunner
automountServiceAccountToken: true

# Role to collect rules from sensor namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eventsrunner-role
  namespace: eventsrunner
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - watch
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eventsrunner-role-binding
  namespace: eventsrunner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eventsrunner-role
subjects:
  - kind: ServiceAccount
    name: eventsrunner-service-account
    namespace: eventsrunner