name: ci
on:
  pull_request:
    branches: [main, develop]

env:
  go_version: 1.17
  k8s_test_image_1: rancher/k3s:v1.23.4-k3s1
  k8s_test_image_2: rancher/k3s:v1.22.7-k3s1
  k8s_test_image_3: rancher/k3s:v1.21.10-k3s1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: go build ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k3s_k8s_image:
          - "${{ env.k8s_test_image_1 }}"
          - "${{ env.k8s_test_image_2 }}"
          - "${{ env.k8s_test_image_3 }}"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Create Simple K8s Cluster
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: cluster
          args: >-
            --image=${{ matrix.k3s_k8s_image }}
      - name: Run tests
        run: go test -v ./... -coverprofile coverage.out
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        if: ${{ matrix.k8s_k8s_image == env.k8s_test_image_1 }}
        with:
          files: coverage.out
          fail_ci_if_error: true

  build-docker-image-and-run-int-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eventsrunner-k8s-sensor:${{ github.sha }} .
      - name: Create K8s Cluster
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: cluster
          args: >-
            --image=${{ env.k8s_test_image_1 }}
            --agents=1
      - name: Upload Docker Image to K8s Cluster
        run: k3d image import -c cluster ${{ secrets.DOCKERHUB_USERNAME }}/eventsrunner-k8s-sensor:${{ github.sha }}

