name: Build and Test
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build ./...

  test_with_k8s_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Create Simple K8s Cluster
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: "cluster-latest"
          args: >-
            --image=rancher/k3s:v1.23.1-rc1-k3s1
            --kubeconfig-update-default
            --kubeconfig-switch-context
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests
        run: go test ./...