name: Build and Test
on:
  pull_request:
    branches: [ main ]

env:
  go_version: 1.17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go_version }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: go build ./...

  test_with_k8s:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k3s_k8s_image:
          - rancher/k3s:v1.23.1-rc1-k3s1
          - rancher/k3s:v1.22.5-k3s1
          - rancher/k3s:v1.21.8-k3s1
      fail-fast: false
    steps:
      - name: Create Simple K8s Cluster
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: cluster-${{ env.GITHUB_JOB }}
          args: >-
            --image=${{ matrix.k3s_k8s_image }}
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: go test ./...