name: release
on:
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    # if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Semver Release
        uses: K-Phoen/semver-release-action@v1.2.0
        id: release-tag
        with:
          release_strategy: 'none'
          release_branch: 'develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build release image
        run: echo ${{ steps.release-tag.outputs.tag }}

  # refresh-go-report:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Refresh Go Report
  #       uses: creekorful/goreportcard-action@v1.0


