name: release
on:
  push:
    branches: [develop]

jobs:
  create-release:
    runs-on: ubuntu-latest
    # if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Login into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Semver Release
        uses: K-Phoen/semver-release-action@v1.2.0
        id: release-tag
        with:
          release_strategy: 'none'
          release_branch: 'develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build release image
        run: DOCKER_BUILDKIT=1 docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/eventsrunner-k8s-sensor:${{ steps.release-tag.outputs.tag }} .




