name: release
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Semver Release
        uses: K-Phoen/semver-release-action@v1.3.0
        id: release-tag
        with:
          release_strategy: "none"
          release_branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build release image
        run: DOCKER_BUILDKIT=1 docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/eventsrunner-k8s-sensor:${{ steps.release-tag.outputs.tag }} .
      - name: Push release image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/eventsrunner-k8s-sensor:${{ steps.release-tag.outputs.tag }}
      - name: Create/Update the tag
        uses: julb/action-manage-tag@v1
        with:
          name: ${{ steps.release-tag.outputs.tag }}
          state: present
          from: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.release-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  refresh-go-report:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh Go Report
        uses: creekorful/goreportcard-action@v1.0


